[project]
name = "mirage"
version = "2.0.0"
description = "Simulating Gravitational Microlensing"
authors = [
  { name = "JordanKoeller", email = "jkoeller12@gmail.com" },
  { name = "DavidPooley", email = "dpooley@trinity.edu" }
]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
  "dask",
  "dask[distributed]",
#  "dask-cloudprovider[aws]",
  "numpy",
  "astropy",
  "bokeh",
  "scipy",
  "PyYAML",
  "cython",
  "hurry.filesize",
  "pandas",
  "ruamel.yaml",
  "frozendict"
]

[project.optional-dependencies]
dev = [
  "matplotlib",
  "pytest",
  "mockito",
]

[project.urls]
Repo = "https://github.com/jordankoeller/mirage"

[build-system]
requires = ["setuptools", "cython", "numpy"]
build-backend = "setuptools.build_meta"

# [tool.setup-tools]
# ext-modules = [
#   {
#     name="mirage.calc.tracers.micro_tracer_helper",
#     sources = ["mirage/calc/tracers/micro_tracer_helper.py"],
#     include-dirs=["numpy.get-include"],
#     extra-compile-args=["-O3", "-fopenmp"],
#     extra-link-args=["-O3", "-fopenmp"],
#   }
# ]

[tool.ruff]
line-length = 88
indent-width = 2
lint.ignore = [ 'F403' ]
