[project]
name = "mirage"
version = "2.0.0"
description = "Simulating Gravitational Microlensing"
authors = [
  { name = "JordanKoeller", email = "jkoeller12@gmail.com" },
  { name = "DavidPooley", email = "dpooley@trinity.edu" }
]
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
  "dask",
  "dask[distributed]",
  "dask-cloudprovider[aws]",
  "numpy",
  "astropy",
  "bokeh",
  "scipy",
  "PyYAML",
  "cython",
  "hurry.filesize",
  "pandas",
  "ruamel.yaml",
  "frozendict"
]

[project.optional-dependencies]
dev = [
  "matplotlib",
  "pytest",
  "mockito",
]

[project.urls]
Repo = "https://github.com/jordankoeller/mirage"

[tool.ruff]
line-length = 88
indent-width = 2
lint.ignore = [ 'F403' ]
